apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-user
  labels: &labels
    app.kubernetes.io/name: pool-user
    app.kubernetes.io/component: component-explorer
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: pool-user
          image: ghcr.io/viva-con-agua/pool-user
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 1323
          readinessProbe:
            httpGet:
              port: http
          livenessProbe:
            httpGet:
              port: http
          resources:
            limits:
              memory: 100Mi
              cpu: 10m # 10 milli-cores = 1% of a core
