apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pool-backend-db-storage
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
