apiVersion: v1
kind: Service
metadata:
  name: pool-user-db
  labels: &labels
    app.kubernetes.io/name: pool-user-db
    app.kubernetes.io/component: component-explorer
spec:
  selector: *labels
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
