apiVersion: v1
kind: Service
metadata:
  namespace: pool-backend
  name: pool-backend
  labels: &labels
    app.kubernetes.io/name: pool-backend
    app.kubernetes.io/component: component-explorer
spec:
  selector: *labels
  ports:
    - name: http
      port: 80
      targetPort: 1323
