apiVersion: v1
kind: Service
metadata:
  name: pool-user
  labels: &labels
    app.kubernetes.io/name: pool-user
    app.kubernetes.io/component: component-explorer
spec:
  selector: *labels
  ports:
    - name: http
      port: 80
      targetPort: http
